spring.application.name=management

spring.datasource.url=jdbc:postgresql://localhost:5432/CarManagement
spring.datasource.continue-on-error=true

spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB
server.tomcat.max-part-count=-1

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

logging.level.root=WARN

logging.level.com.car.management=DEBUG

logging.level.org.springframework.security=WARN

logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

logging.pattern.console=%d{HH:mm:ss.SSS} %highlight(%-5level) %cyan(%logger{36}) - %msg%n

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=car.base.pl@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.profiles.include=secrets

app.frontend.url=http://localhost:4200
app.backend.url=http://localhost:8080
